// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBPNh82Fc0wRfvxmoaQbfKEYMYal7jwMM',
    appId: '1:519069807777:web:c431ac2eede3b8820f6ce0',
    messagingSenderId: '519069807777',
    projectId: 'chatapp-c22c6',
    authDomain: 'chatapp-c22c6.firebaseapp.com',
    storageBucket: 'chatapp-c22c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuDUWb8EADpq-LIxDudpib1RX0WbeYHeU',
    appId: '1:519069807777:android:1ede4e5659b264a50f6ce0',
    messagingSenderId: '519069807777',
    projectId: 'chatapp-c22c6',
    storageBucket: 'chatapp-c22c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaAFR7yTK1eLXRyMhqJV7GWUxe8GChvdA',
    appId: '1:519069807777:ios:fc6fb646e76b3f6d0f6ce0',
    messagingSenderId: '519069807777',
    projectId: 'chatapp-c22c6',
    storageBucket: 'chatapp-c22c6.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
